name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install package and tools
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest ruff
      - name: Lint (ruff)
        run: ruff check .
      - name: Tests (pytest)
        run: pytest -q

